name: Build Gradle application

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: false
        type: string
        description: Path to the Dockerfile
        default: 'Dockerfile'
      image-tag:
        required: false
        type: string
        description: Docker image tag
        default: 'latest'
    outputs:
      image:
        description: Google Artifact Registery image
        value: ${{ jobs.build-push-image.outputs.image }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Push Docker Image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          dockerfile: ${{ inputs.dockerfile-path }}
          tag: ${{ inputs.image-tag }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
