name: Build & test PR

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '21'
      gradle-run-tasks:
        required: false
        type: string
        description: Gradle tasks to run
        default: './gradlew --configuration-cache build shadowJar'

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - uses: gradle/actions/setup-gradle@v4
      - run: ${{ inputs.gradle-run-tasks }}