name: Gradle Dependency Submission

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: "25"

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # ratchet:step-security/harden-runner@v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # ratchet:actions/setup-java@v5.6.0
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: gradle

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # ratchet:gradle/actions/dependency-submission@v6.2.0
