name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      pnpm-version:
        required: false
        type: string
        description: pnpm version to build with
        default: '10'
      node-version:
        required: false
        type: string
        description: Node version to build with
        default: '22'
      image-tag:
        required: false
        type: string
        description: Docker image tag
        default: 'latest'
      build-command:
        required: false
        type: string
        description: Command to build the application
        default: 'pnpm run build'
    secrets:
      ASTRO_KEY:
        required: false
        description: Optional Astro key

    outputs:
      image:
        description: Google Artifact Registery image
        value: ${{ jobs.build-push-image.outputs.image }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies for client
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
          pnpm config set @navikt:registry https://npm.pkg.github.com
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build app
        run: ${{ inputs.build-command }}
        env:
          ASTRO_KEY: ${{ secrets.ASTRO_KEY }}

      - name: Push Docker Image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          tag: ${{ inputs.image-tag }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
