name: Squawk Migration Lint

on:
  workflow_call:

jobs:
  squawk-migration-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # ratchet:step-security/harden-runner@v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Find modified migrations
        run: |
          modified_migrations=$(git diff --diff-filter=d --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF 'src/main/resources/db/migration/*.sql' | tr '\n' ' ')
          echo "Migration files: $modified_migrations"
          echo "file_names=$modified_migrations" >> $GITHUB_OUTPUT
        id: modified-migrations

      - name: Run Squawk Lint
        uses: sbdchd/squawk-action@8d113898e16c6cfd417ceba848b0edad97882be3 # ratchet:sbdchd/squawk-action@v2
        with:
          files: ${{ steps.modified-migrations.outputs.file_names }}
